// Seeded exercise library: how to do it, cues, mistakes, safety.
// Keyed by exercise_id as used throughout prescriptions.

export type ExerciseEntry = {
  id: string;
  name: string;
  aliases?: string[];
  primary_muscle: string;
  pattern: 'squat' | 'hinge' | 'push_horizontal' | 'push_vertical' | 'pull_horizontal' | 'pull_vertical' | 'lunge' | 'carry' | 'core' | 'isolation' | 'conditioning';
  equipment?: string[];
  how_to: string[];
  cues: string[];
  mistakes: string[];
  safety?: string[];
  tracks?: 'weight_reps' | 'reps_only' | 'time';
};

export const EXERCISE_LIBRARY: Record<string, ExerciseEntry> = {
  // ---------- PUSH ----------
  incline_db_press: {
    id: 'incline_db_press',
    name: 'Incline DB Press',
    primary_muscle: 'Upper chest',
    pattern: 'push_horizontal',
    equipment: ['Dumbbells', 'Incline bench'],
    how_to: [
      'Set bench to 30°. Dumbbells start at the outside of the shoulders.',
      'Press up and slightly in, stopping just before the bells touch.',
      'Control down to the start — 2-3 seconds eccentric.',
    ],
    cues: ['Shoulder blades tucked down and back', 'Wrists stacked over elbows', 'Feet planted, ribcage down'],
    mistakes: ['Bench too steep (>45° turns it into OHP)', 'Elbows flared to 90° — aim for ~60°', 'Bouncing at the bottom'],
    safety: ['If a rep fails, just drop the dumbbells laterally — do NOT try to rack on your chest.'],
    tracks: 'weight_reps',
  },
  flat_db_press: {
    id: 'flat_db_press',
    name: 'Flat DB Press',
    primary_muscle: 'Chest',
    pattern: 'push_horizontal',
    equipment: ['Dumbbells', 'Flat bench'],
    how_to: ['Dumbbells at mid-chest level, slight arch.', 'Press up, squeezing chest at top.', 'Lower until you feel a stretch.'],
    cues: ['Elbows ~45° from torso', 'Full stretch at the bottom', 'Don\'t lock out hard'],
    mistakes: ['Letting elbows flare to 90°', 'Bouncing', 'Half reps at the top'],
    tracks: 'weight_reps',
  },
  seated_db_ohp: {
    id: 'seated_db_ohp',
    name: 'Seated DB Overhead Press',
    primary_muscle: 'Shoulders',
    pattern: 'push_vertical',
    equipment: ['Dumbbells', 'Bench with back support'],
    how_to: ['Back tight against pad. Dumbbells at ear level.', 'Press straight up until elbows just short of lockout.', 'Lower under control.'],
    cues: ['Ribcage down — don\'t arch lower back', 'Press up, not forward', 'Elbows slightly in front of wrists'],
    mistakes: ['Lumbar hyperextension', 'Pressing from too low (below ear = shoulder impingement risk)'],
    safety: ['Any sharp shoulder pain — stop. Switch to landmine press or high-incline DB press.'],
    tracks: 'weight_reps',
  },
  db_lateral_raise: {
    id: 'db_lateral_raise',
    name: 'DB Lateral Raise',
    primary_muscle: 'Side delts',
    pattern: 'isolation',
    equipment: ['Dumbbells'],
    how_to: ['Slight forward lean. Dumbbells held with thumbs slightly down.', 'Raise out to the side, leading with elbows.', 'Stop at shoulder height — don\'t go higher.'],
    cues: ['Think "pouring a jug" — pinky up at the top', 'Lead with the elbow', 'Pause 1s at the top'],
    mistakes: ['Swinging / using momentum', 'Shrugging the traps', 'Going too heavy — this is a feel lift'],
    tracks: 'weight_reps',
  },
  face_pull: {
    id: 'face_pull',
    name: 'Face Pull',
    primary_muscle: 'Rear delts / upper back',
    pattern: 'pull_horizontal',
    equipment: ['Cable', 'Rope attachment'],
    how_to: ['Rope at forehead height. Step back to take the slack.', 'Pull rope toward your forehead, hands separating at the finish.', 'Thumbs pointing back, elbows high.'],
    cues: ['External rotation at the end — think "double biceps pose"', 'Light weight, slow tempo', 'Squeeze 1-2s'],
    mistakes: ['Going too heavy and rowing it instead', 'Elbows dropping'],
    tracks: 'weight_reps',
  },
  tricep_pressdown: {
    id: 'tricep_pressdown',
    name: 'Tricep Pressdown',
    primary_muscle: 'Triceps',
    pattern: 'isolation',
    equipment: ['Cable', 'Rope or straight bar'],
    how_to: ['Elbows pinned to sides, grip just above shoulder height.', 'Press down until arms are locked straight.', 'Control the return to ~90° at the elbow.'],
    cues: ['Elbows do not move', 'Squeeze lockout for 1s', 'Slight forward lean'],
    mistakes: ['Elbows flaring forward', 'Using lat swing', 'Not locking out'],
    tracks: 'weight_reps',
  },
  overhead_tricep_ext: {
    id: 'overhead_tricep_ext',
    name: 'Overhead Tricep Extension',
    primary_muscle: 'Triceps (long head)',
    pattern: 'isolation',
    equipment: ['Cable', 'Dumbbell', 'or EZ bar'],
    how_to: ['Arms overhead, elbows close to ears.', 'Lower behind the head until you feel a deep stretch.', 'Extend to lockout.'],
    cues: ['Elbows stay narrow', 'Full stretch at the bottom', 'Ribcage down'],
    mistakes: ['Elbows flaring wide', 'Short range of motion'],
    safety: ['Feel it in the elbow joint? Reduce load and shorten the ROM.'],
    tracks: 'weight_reps',
  },

  // ---------- PULL ----------
  pull_ups_quality: {
    id: 'pull_ups_quality',
    name: 'Pull-ups (quality)',
    primary_muscle: 'Lats',
    pattern: 'pull_vertical',
    equipment: ['Pull-up bar'],
    how_to: ['Dead hang start, full extension.', 'Pull chest to bar, chin clears.', 'Lower slowly to full hang.'],
    cues: ['Pull elbows down and back', 'Chest up, not chin up', '2-3s eccentric'],
    mistakes: ['Kipping', 'Not reaching full dead hang', 'Rounding shoulders forward'],
    safety: ['Add band assistance rather than cheating with momentum.'],
    tracks: 'weight_reps',
  },
  pull_ups_emom: {
    id: 'pull_ups_emom',
    name: 'Pull-ups (EMOM)',
    primary_muscle: 'Lats',
    pattern: 'pull_vertical',
    equipment: ['Pull-up bar', 'Clock'],
    how_to: ['Every minute on the minute, complete target reps.', 'Rest for the remainder of the minute.', 'Stop before form breaks.'],
    cues: ['Keep quality high — if reps slow below target, stop a round early', 'Breathe on the descent'],
    mistakes: ['Grinding reps with bad form late in the workout'],
    tracks: 'reps_only',
  },
  neutral_pulldown: {
    id: 'neutral_pulldown',
    name: 'Neutral-Grip Pulldown',
    primary_muscle: 'Lats',
    pattern: 'pull_vertical',
    equipment: ['Cable', 'Neutral-grip attachment'],
    how_to: ['Palms facing each other, arms fully extended.', 'Pull handle to upper chest.', 'Control back to a full stretch.'],
    cues: ['Chest up, lean back ~10°', 'Pull with the elbows, not the hands', 'Stretch lats at the top'],
    mistakes: ['Using momentum', 'Only half the range'],
    tracks: 'weight_reps',
  },
  chest_supported_row: {
    id: 'chest_supported_row',
    name: 'Chest-Supported Row',
    primary_muscle: 'Mid-back',
    pattern: 'pull_horizontal',
    equipment: ['Incline bench', 'Dumbbells or T-bar'],
    how_to: ['Chest on the pad, arms hanging straight.', 'Row elbows back, squeezing shoulder blades.', 'Lower under control.'],
    cues: ['Elbows track along the body', 'No jerking', '1s pause at top'],
    mistakes: ['Pulling with the arms instead of the back', 'Elbows flaring wide'],
    tracks: 'weight_reps',
  },
  single_arm_row: {
    id: 'single_arm_row',
    name: 'Single-Arm DB Row',
    primary_muscle: 'Lats',
    pattern: 'pull_horizontal',
    equipment: ['Dumbbell', 'Bench'],
    how_to: ['Knee and hand on bench, flat back.', 'Row DB to hip, elbow tight.', 'Control to full stretch.'],
    cues: ['Hip-pocket row, not armpit', 'Don\'t rotate torso to cheat', 'Squeeze 1s'],
    mistakes: ['Torso rotation / body english', 'Shrugging at the top'],
    tracks: 'weight_reps',
  },
  rear_delt_fly: {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    primary_muscle: 'Rear delts',
    pattern: 'isolation',
    equipment: ['Dumbbells or reverse pec deck'],
    how_to: ['Hinge forward, slight elbow bend.', 'Raise arms out to sides to shoulder height.', 'Lower slow.'],
    cues: ['Lead with elbows', 'Thumbs slightly down', 'Light weight, squeeze hard'],
    mistakes: ['Going too heavy and swinging', 'Shrugging'],
    tracks: 'weight_reps',
  },
  incline_db_curl: {
    id: 'incline_db_curl',
    name: 'Incline DB Curl',
    primary_muscle: 'Biceps (long head)',
    pattern: 'isolation',
    equipment: ['Incline bench', 'Dumbbells'],
    how_to: ['Bench at 60°, arms hanging behind body.', 'Curl without moving the elbow forward.', 'Full stretch at the bottom.'],
    cues: ['Elbows stay behind torso', 'Supinate the wrist through the curl', 'Don\'t swing'],
    mistakes: ['Elbows coming forward (turns it into a front raise)', 'Not fully extending'],
    tracks: 'weight_reps',
  },
  hammer_curl: {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    primary_muscle: 'Brachialis / biceps',
    pattern: 'isolation',
    equipment: ['Dumbbells'],
    how_to: ['Neutral grip (thumbs up). Elbows at sides.', 'Curl up without rotating wrist.', 'Control the descent.'],
    cues: ['Thumbs aim at shoulder at top', 'Squeeze 1s', 'No swinging'],
    mistakes: ['Body english', 'Half reps'],
    tracks: 'weight_reps',
  },

  // ---------- LOWER ----------
  ffe_split_squat: {
    id: 'ffe_split_squat',
    name: 'Front-Foot-Elevated Split Squat',
    primary_muscle: 'Quads / glutes',
    pattern: 'lunge',
    equipment: ['Dumbbells', 'Low platform (3-6 in)'],
    how_to: ['Front foot on platform, back foot 2-3 ft back.', 'Drop back knee straight down to a soft tap.', 'Drive through front heel.'],
    cues: ['Torso tall, slight forward lean', 'Back knee kisses the floor, doesn\'t crash', 'Front shin vertical-ish'],
    mistakes: ['Front knee caving in', 'Pushing off the back foot', 'Too narrow a stance'],
    safety: ['Do all reps on one leg before switching. Start light — balance matters more than load early.'],
    tracks: 'weight_reps',
  },
  rdl_barbell: {
    id: 'rdl_barbell',
    name: 'Barbell RDL',
    aliases: ['Romanian Deadlift'],
    primary_muscle: 'Hamstrings / glutes',
    pattern: 'hinge',
    equipment: ['Barbell'],
    how_to: [
      'Start standing, bar at the top of the hip crease.',
      'Hinge at the hips — push butt back, soft knees.',
      'Lower the bar along the thighs until you feel a deep hamstring stretch (bar around mid-shin to just below knee).',
      'Drive hips forward to stand tall.',
    ],
    cues: ['Bar STAYS glued to your legs', 'Lats engaged — "protect your armpits"', 'Push the floor away, don\'t pull the bar up', 'Neutral spine — chin tucked, not looking up'],
    mistakes: ['Squatting it (too much knee bend)', 'Rounding lower back at the bottom', 'Bar drifting forward away from legs', 'Going below the stretch point with bad form'],
    safety: ['If your back rounds, stop the rep short. Protecting neutral spine is non-negotiable.', 'Mixed grip or straps for heavy sets — don\'t let grip limit hamstring work.'],
    tracks: 'weight_reps',
  },
  hamstring_curl: {
    id: 'hamstring_curl',
    name: 'Hamstring Curl',
    primary_muscle: 'Hamstrings',
    pattern: 'isolation',
    equipment: ['Machine (seated or lying)'],
    how_to: ['Align knee joint with machine pivot.', 'Curl heels under, squeeze.', 'Control the return — 2s eccentric.'],
    cues: ['Point toes to dorsiflex for more hamstring involvement', 'Squeeze at the bottom', 'Slow eccentric'],
    mistakes: ['Lifting hips off the pad', 'Using momentum'],
    tracks: 'weight_reps',
  },
  hip_thrust: {
    id: 'hip_thrust',
    name: 'Barbell Hip Thrust',
    primary_muscle: 'Glutes',
    pattern: 'hinge',
    equipment: ['Barbell', 'Bench', 'Bar pad'],
    how_to: ['Shoulders on bench, feet planted shoulder-width.', 'Drive through heels, finish with hip lockout and glute squeeze.', 'Lower to just above the floor.'],
    cues: ['Chin tucked, ribs down at the top', 'Knees push slightly out', 'Pause 1-2s at lockout'],
    mistakes: ['Hyperextending lower back at top (squeeze glutes instead)', 'Feet too close or too far', 'Pushing through toes instead of heels'],
    tracks: 'weight_reps',
  },
  calf_raise: {
    id: 'calf_raise',
    name: 'Calf Raise',
    primary_muscle: 'Calves',
    pattern: 'isolation',
    equipment: ['Machine or step with DB'],
    how_to: ['Balls of feet on the edge.', 'Lower heels for a deep stretch.', 'Press up onto toes, pause 1s at top.'],
    cues: ['Full range — deep stretch, full contraction', 'Slow down on the stretch', 'No bounce'],
    mistakes: ['Partial reps', 'Bouncing'],
    tracks: 'weight_reps',
  },

  // ---------- CORE ----------
  hanging_knee_raise: {
    id: 'hanging_knee_raise',
    name: 'Hanging Knee Raise',
    primary_muscle: 'Abs',
    pattern: 'core',
    equipment: ['Pull-up bar'],
    how_to: ['Dead hang, active shoulders.', 'Raise knees to chest, curling pelvis.', 'Lower under control.'],
    cues: ['Curl the pelvis — not just hip flexion', 'No swinging', 'Exhale at the top'],
    mistakes: ['Just hip flexing (knees up but no pelvic curl)', 'Swinging'],
    tracks: 'reps_only',
  },
  hanging_leg_raise: {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    primary_muscle: 'Abs',
    pattern: 'core',
    equipment: ['Pull-up bar'],
    how_to: ['Dead hang. Straight legs.', 'Raise legs to parallel (or higher), curling the pelvis.', 'Lower slow.'],
    cues: ['Pelvic curl at the top', 'Don\'t swing', 'Active shoulders'],
    mistakes: ['Bent knees (becomes a knee raise)', 'Swinging'],
    tracks: 'reps_only',
  },
  side_plank: {
    id: 'side_plank',
    name: 'Side Plank',
    primary_muscle: 'Obliques / QL',
    pattern: 'core',
    how_to: ['On forearm, body straight, hips stacked.', 'Hold for the prescribed time.', 'Switch sides.'],
    cues: ['Hips high — don\'t sag', 'Squeeze glutes', 'Breathe normally'],
    mistakes: ['Hips dropping', 'Holding breath'],
    tracks: 'time',
  },
  dead_bug: {
    id: 'dead_bug',
    name: 'Dead Bug',
    primary_muscle: 'Deep core',
    pattern: 'core',
    how_to: ['Lie on back, arms up, knees at 90°.', 'Extend opposite arm and leg while keeping lower back pressed into floor.', 'Return, switch.'],
    cues: ['Lower back stays pressed to floor', 'Slow and controlled', 'Exhale on extension'],
    mistakes: ['Arching lower back as limbs extend', 'Going fast'],
    tracks: 'reps_only',
  },
  ab_circuit: {
    id: 'ab_circuit',
    name: 'Ab Circuit',
    primary_muscle: 'Core',
    pattern: 'core',
    how_to: ['Follow the prescribed circuit (varies by day).', 'Keep form strict — no momentum.'],
    cues: ['Quality over quantity', 'Control every rep'],
    mistakes: ['Rushing through to finish'],
    tracks: 'time',
  },
};

export function getExercise(id: string): ExerciseEntry | null {
  return EXERCISE_LIBRARY[id] ?? null;
}

export function prettyName(id: string): string {
  const e = EXERCISE_LIBRARY[id];
  if (e) return e.name;
  return id.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}
